### ISSUE TITLE
Create the db module

### ISSUE THREAD

**Issue by NicksPatties** [NicksPatties/sweet#61]
# Overview

The `db` module is in charge of managing connections, adding data to, and reading from the `reps` database.

# Tasks

- [x] Create the database with [the correct schema](#the-correct-schema) if it doesn't exist
- [x] Connect to the database after the end of a rep
- [x] Save the database file at `~/.config/sweet/sweet.db` or at a location specified by `SWEET_DB_LOCATION` environment variable
- [x] Create a function to take ~a file~ a string, and hash its contents.
  - Used for the `hash` column of the `reps` database
- [x] Save the data as a rep struct
- [x] Modify the `printResults` function to take a rep struct as input
  - Check the printResults function by returning a string and unit testing it
- [x] Write a function to save a rep struct into the database
  - [x] Convert a `Rep` struct to a query
  - [x] Call the function with a rep query

# Success criteria

- [x] Unit tests for the previous tasks pass
- [x] When I run `sweet`, and complete an exercise
  - [x] the recorded events are converted into a `rep`
  - [x] I can connect to the database
  - [x] I can write my data into the database
  - [x] I can disconnect successfully
- [x] I can do the same as above with a different `SWEET_DB_LOCATION`

<details>
<summary>Notes</summary>

## The correct schema

```sql
CREATE TABLE if not exists reps(
  id integer primary key autoincrement not null,
  -- md5 hash of the exercise file's contents
  hash string NOT NULL,
  -- start time in unix milliseconds
  start integer not null,
  -- end time in unix milliseconds
  end integer not null,
  -- name of the exercise file, includes extension if present
  name text not null,
  -- language: extension of the exercise file, or "" if there is none.
  lang text,
  -- words per minute
  wpm real not null check(wpm >= 0.0),
  -- raw words per minute
  raw real not null check(raw >= 0.0),
  -- duration: duration of rep in **nanoseconds**
  dur integer not null check(dur >= 0),
  -- accuracy: float between [0, 100]
  acc real not null check(acc >= 0.0),
  -- mistakes: must be gte 0
  miss integer not null check(miss >= 0),
  -- uncorrected errors: must be gte 0
  errs integer not null check(errs >= 0),
  -- array of events, events are separated by '\n'
  events text not null
);
```

### Adding constraints to SQL columns

use `CHECK` function when defining the db schema.

## Creating a database in Go

```go
func initDatabase(dbPath string) (*sql.DB, error) {
    // Open a connection to the SQLite database
    db, err := sql.Open("sqlite3", dbPath)
    if err != nil {
        return nil, fmt.Errorf("failed to open database: %v", err)
    }

    // Test the connection
    err = db.Ping()
    if err != nil {
        db.Close()
        return nil, fmt.Errorf("failed to connect to database: %v", err)
    }

    // Create a sample table
    _, err = db.Exec(`
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL,
            email TEXT UNIQUE NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    `)
    if err != nil {
        db.Close()
        return nil, fmt.Errorf("failed to create table: %v", err)
    }

    return db, nil
}
```

## Getting the default user config directory

util/util.go:35
```go
func GetConfigDirectory() string {

	exeName := "sweet"

	configDir, err := os.UserConfigDir()
	if err != nil {
		l.Fatalf("Failed to get user's config directory: %s\n", err.Error())
	}
	return path.Join(configDir, exeName)
}
```
- This doesn't make the directory if it doesn't exist, but I'm doing the same thing in multiple places. 

## Checking for an environment variable

```go
// taken from cmd/root/sweet.go:545
var exercisesDir string
if envDir := os.Getenv("SWEET_EXERCISES_DIR"); envDir != "" {
	exercisesDir = envDir

} else {
	var configDir string
	configDir, err = os.UserConfigDir()
	if err != nil {
		return
	}
	exercisesDir = path.Join(configDir, "sweet", "exercises")
}
```

## The `rep` struct

```go
type Rep struct {
  hash string
  start time.Time // use
  end time.Time
  name string
  lang string
  wpm float64 // thought this was a float, but I guess not?
  dur time.Duration // 
  acc float64
  miss int
  errs int
  events []event // this event struct makes me want to move this struct into the sweet.go function
}
```

## Converting an array of `event` structs to a string

```go
// assuming ev is an event, we can convert it to a string like this
eventsString := ""
for _, ev := range events {
  eventsString += ev.String() + "\n"
}
```

## Hashing files

When you hash a file, **you're only hashing the contents**. The name of the file doesn't matter.

Consider two files, `one` and `two`, that both have the contents `hello`.

```sh
echo "hello" >> one
echo "hello" >> two
```

When both are hashed, their output is the same.

```sh
md5sum one two
# b1946ac92492d2347c6235b4d2611184  one
# b1946ac92492d2347c6235b4d2611184  two
```

## Inserting a row of data in Go

```go
func InsertRep(db *sql.DB, rep Rep) (int64, error) {
  // ...
  
	query := `insert into reps (
	    hash, start, end, name, lang, wpm,
	    raw, dur, acc, miss, errs, events
	   ) values (
	   	?, ?, ?, ?, ?, ?,
	   	?, ?, ?, ?, ?, ?
	   );`

	result, err := db.Exec(query,
		hash, start, end, name, lang, wpm,
		raw, dur, acc, miss, errs, events,
	)

	if err != nil {
		return 0, err
	}

	return result.LastInsertId()
}
```

</details>
