### ISSUE TITLE
Create the `stats` command

### ISSUE THREAD

**Issue by NicksPatties** [NicksPatties/sweet#63]
# Overview

The `stats` command lets users view their statistics, to easily see whether their typing ability is improving.

Users can filter their stats analysis by specifying a date range and a specific set of columns. The command prints out interesting metrics, a graph of the words per minute, and a table of the reps used to calculate the statistics.

Parse the arguments provided by the stats command, ~and return a database query that retrieves that specific data.~ and return a query object that filters out data from the returned set of rows.

# Sub-tasks

- [x] Make selection flags: `--wpm --raw --acc --miss --errs --name --lang --dur`
  - Order of the appearance of the flags _doesn't matter_. The columns will all appear in the same order. 
- [x] `--name={{filename}}` selects only exercises with the given file name
  - blob selection? `--name=*burger*` --> `select ... where name like '%burger%'`
- [x] `--lang={{lang}}` selects only exercises with a given file extension
- [x] `--start` flag YYYY-MM-DD, or {{N}}[H,D,W,M,Y] where N is a positive integer. Default is midnight today.
  - H - hour, D - day, W - week, M - month, Y - year
  - Make a `--since` flag, alias for `--start`
- [x] Make an `--end` flag YYYY-MM-DD, default is today right before midnight of the next day, must be later than start
- [x] Write unit tests to verify the correct queries are produced

# Success criteria

Verify that for the following commands, the correct query is produced:

1. [x] `sweet stats`
2. [x] `sweet stats --since=2D`
3. [x] `sweet stats --start=2024-10-01 --end=2024-11-01`
4. [x] `sweet stats --wpm --acc`
5. [x] `sweet stats --lang=py`
6. [x] `sweet stats --name=tuple.py --acc --errs`

<details>
<summary>Notes</summary>

# Notes

### Should I modify the query, or get everything and filter the result?

If I modify the query, then I
- **need to fetch all of my rows each time I query the database (this is bad)**

If I query everything and then filter the result, then I
- have an easier time filtering out columns
- have **all** of the data for each row, in case I need it for other UI elements (for instance, comparing wpm to raw, even if I dont query it)

**I should do both.**
- Modify the query when I want to
  - get items in a specific date range
  - get items that have a column that matches a specific value
- Choose which objects to render when I
  - pick out which columns to display
  - pick which columns should be plotted

### Modifying the arguments of a cobra command for testing

```go
	type testCase struct {
		name    string
		in      []string
		want    string
		wantErr bool
	}

  // a duplicate of the command that also runs test cases
	var mockCmd = func(tc testCase) *cobra.Command {
		cmd := &cobra.Command{
			Args: cobra.MaximumNArgs(1),
			Run: func(cmd *cobra.Command, args []string) {
				got, err := queryFromArgs(cmd, now)
				if err == nil && tc.wantErr {
					t.Errorf("%s wanted error, got nil", tc.name)
				}

				if got != tc.want {
					t.Errorf("%s\n"+
						"  got:  %s\n"+
						"  want: %s\n",
						tc.name, got, tc.want)
				}
			},
		}
		setStatsCommandFlags(cmd)
    // this is the important line here!
    // it assigns the elements in the tc.in array to the arguments
    // of the command.
    // functions like `cmd.Flag(var).Value.String()` will still work.
		cmd.SetArgs(tc.in) 
		return cmd
	}
```

## Commands with a single dash in a cobra application

Single dash commands are used with shorthand, and shorthand commands are only allowed to have one letter within them. This is a design descision by the cobra commander package maintainers.

To work around this, **I'm just going to use `--` commands to show the columns in the repository**.

Alternatively, I could just use the `flags` library in conjunction with cobra commands, but that seems like a hassle to combine the two together after I've come this far.

## Detecting the order in which flags were provided in a cobra command

The following iterates through all the flags defined in the application.

```go
// requires me importing the pflag package
import "github.com/spf13/pflag"

// ...

cmd.LocalFlags().VisitAll(func(flag *pflag.Flag) {
  // This gets all the flags in the order in which they are defined.
	// NOT in the order in which they are passed in.
	fmt.Printf("flag: %v\n", flag)
})
```

However, **this is not the same as viewing the flags in the order in which they are used.**

However, Instead of flags, I can make the arguments... which would then mean I can modify the order of those arguments. But then I would have to document them.

_I don't know which solution is better at the moment, so I'll just pick one option and stick to it._ Let's just have the arguments be flags right now, and control their visibility, but not their order. If I want to worry about their order.
</details>

**Comment by NicksPatties** [comment]
Merged with #73
