### ISSUE TITLE
Implement `sweet stats` UI

### ISSUE THREAD

**Issue by NicksPatties** [NicksPatties/sweet#65]
# Overview

Once the stats data has been retrieved, it needs to be displayed on the screen. There are three UI components to display:

1. A metrics breakdown of the stats that were queried
```txt
stats from today ({{ .startDate }} to {{ .endDate }}):

          avg     min     max     1st     last     delta
wpm       60      50      65      53      63      +10
mistakes  4       0       9       4       0       -4
errors    0.2     0       3       1       0       -1
accuracy  98.28%  100%    100%    96%     97%     +1%
```
2. A graph of the given metrics (produced by ascii graph)

3. A table of the reps that were retrieved
```txt
reps:
time      filename       lang    wpm     errs    dura    acc
13:43:00  sweet_cmd.go   go      55      1       1m2s    95%
13:43:11  sweet_cmd.go   go      60      0       1m2s    95%
13:43:12  sweet_cmd.go   go      60      3       1m2s    95%
13:50:00  sweet_cmd.go   go      60      2       1m2s    95%
13:53:00  sweet_cmd.go   go      60      0       1m2s    95%
13:43:00  sweet_cmd.go   go      55      0       1m2s    95%
13:43:11  sweet_cmd.go   go      60      1       1m2s    95%
13:43:12  sweet_cmd.go   go      60      0       1m2s    95%
13:50:00  sweet_cmd.go   go      60      0       1m2s    95%
13:53:00  sweet_cmd.go   go      60      0       1m2s    95%
... and 23 more. Try running `sweet stats --table`
```
 
# Sub-tasks

- [x] Print the output of the metrics into a table
- [x] Print a plot using the arrays of the previously mentioned map
- [x] Print the rows returned by SQL into a table
  - ~Truncate after 10 rows~
  - ~Print a message saying use `sweet stats --table` if you wanna see more~
- [x] ~Add `sweet stats --table` flag to only show the table, and avoid truncating the table.~
  - If the output is too big, then just pipe the output into less
	- If it's a feature that people actually want, then it should be requested.

# Success criteria

Unit testing the printing functions can be accomplished by having the functions returning a string, and then comparing strings with expected output within a file.

The expected output will depend on the output produced by the third party libraries, and may not consider color.

<details>
<summary>Notes</summary>

# Notes

## Getting the avg, min, max, first, last, and change of a recorded stat

Here's an example if I need to return the average for just wpm. To get everything for wpm, miss, errs, or acc, I should

```go
// conversion of data from within the rep to a format that can be consumed
// by metrics.
type repData map[string]float64

// These metrics should not be rounded.
// Rounding should only happen when rendering the information.
type metrics struct {
  avg   float64
  min   float64
  max   float64
  first float64
  last  float64
}

// The string of the returned map correspond to the column within a rep.
// For instance, "wpm", or "acc".
// Metrics that are not fetched will not be included in the returned data.
func getMetrics(reps []repData, keys []string) (mmap map[string]metrics) {
	mmap = map[string]metrics{}

	for _, key := range keys {
		first := float64(reps[len(reps)-1][key])
		last := float64(reps[0][key])

		// for avg
		sum := 0.0
		total := float64(len(reps))

		min := math.MaxFloat64
		max := 0.0

		for _, r := range reps {
			if min > r[key] {
				min = r[key]
			} else if max < r[key] {
				max = r[key]
			}
			sum += r[key]
		}

		avg := sum / total
		m := metrics{
			avg:   avg,
			min:   min,
			max:   max,
			first: first,
			last:  last,
		}
		mmap[key] = m
	}
	return mmap
}
```

## Rendering the stats table by myself

```go
// key of stat name "wpm", "acc", and value of an array of floats
// metrics struct is the same as above
type statsTable map[string]metrics

func (table statsTable) String() (s string) {
	// print header
	headerOrder := []string{"avg", "min", "max", "1st", "last", "delta"}
	s += "\t"
	for _, header := range headerOrder {
		s += "\t" + header
	}
	s += "\n"

  // print the rows, one per stat
	statsOrder := []string{"wpm", "acc"}
  // in case I want to print each column of the map in a specific way.
  // must be the same length as the number of headers in the column.
	formatMap := map[string][]string{
		"wpm": {"%.f", "%.f", "%.f", "%.f", "%.f", "%.f"},
		"acc": {"%2.f%%", "%2.f%%", "%2.f%%", "%2.f%%", "%2.f%%", "%2.f%%"},
	}
	for _, key := range statsOrder {
		s += key + "\t\t"
		currMetrics := table[key]
		// avg
		s += fmt.Sprintf(formatMap[key][0]+"\t", currMetrics.avg)
		s += fmt.Sprintf(formatMap[key][1]+"\t", currMetrics.min)
		s += fmt.Sprintf(formatMap[key][2]+"\t", currMetrics.max)
		s += fmt.Sprintf(formatMap[key][3]+"\t", currMetrics.first)
		s += fmt.Sprintf(formatMap[key][4]+"\t", currMetrics.last)
		s += fmt.Sprintf(formatMap[key][5]+"\t", currMetrics.last-currMetrics.first)
		s += "\n"
	}
	return
} 
```

Produces this output with some random data

```txt
                avg     min     max     1st     last    delta
wpm             66      50      66      64      55      -9
acc             95%     90%     100%    97%     98%      1%
```

</details>

**Comment by NicksPatties** [comment]
Completed with #75
